version: '2'

services:
    kafka:
        build: ./Dockerkafka
        ports:
            - "2181:2181"
            - "9092:9092"
    taktstrasse:
        build: ./Dockerjava
        links:
            - kafka
            - activemq
    postgresql: 
        build: ./Dockerpostgres
        ports:
            - "5432:5432"
    activemq:
        build: ./Dockeractivemq
        ports: 
            - "8161:8161"
            - "61616:61616"
    spark:
        build: ./Dockerspark
        ports: 
            - "8080:8080"
            - "7077:7077"
	
	